version: 2.1

jobs:
  ci:
    docker:
      - image: 'cimg/node:20.14'
    steps:
      - checkout
      - run: 
          name: Install proto and moon
          command: |
            bash <(curl -fsSL https://moonrepo.dev/install/proto.sh)

            export PROTO_HOME="$HOME/.proto";
            export PATH="$PROTO_HOME/shims:$PROTO_HOME/bin:$PATH";

            echo "export PROTO_HOME=\"$PROTO_HOME\"" >> "$BASH_ENV"
            echo "export PATH=\"$PATH\"" >> "$BASH_ENV"
            
            # # Bug being tracked: https://github.com/moonrepo/proto/issues/791
            # timeout 5s proto i moon 1.37 || proto i moon 1.37
            proto install
      - run:
          name: Moon check
          command: |
            moon ci check
      - run:
          name: Moon check 2
          command: |
            moon ci -u check
      - run:
          name: Moon check 3
          command: |
            moon ci -u check && moon ci -u check
      - run:
          name: Moon check 4
          command: |
            moon ci -u check
            moon ci -u check
      # - run:
      #     name: Moon Test
      #     command: moon ci test
      # - run: 
      #     name: Moon build
      #     command: moon ci build

workflows:
  pipeline:
    jobs:
      - 'ci'
